// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD142o849En4sc-Nr1NOKEt6XvlZgDQaBo',
    appId: '1:136939587877:web:5fab704c6ae988740232cc',
    messagingSenderId: '136939587877',
    projectId: 'auth-flutter-ec8b3',
    authDomain: 'auth-flutter-ec8b3.firebaseapp.com',
    storageBucket: 'auth-flutter-ec8b3.firebasestorage.app',
    measurementId: 'G-215B32BP70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSOmKUas5HGy0HuJnLCN3tlLpghjuFRV4',
    appId: '1:136939587877:android:9cd2dcb705b187230232cc',
    messagingSenderId: '136939587877',
    projectId: 'auth-flutter-ec8b3',
    storageBucket: 'auth-flutter-ec8b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-UKf86RVfOJMajSzGaCxCwxcEdcUCiM',
    appId: '1:136939587877:ios:350135454dafa6df0232cc',
    messagingSenderId: '136939587877',
    projectId: 'auth-flutter-ec8b3',
    storageBucket: 'auth-flutter-ec8b3.firebasestorage.app',
    androidClientId: '136939587877-avbbu7s79ptogdh5mcouoln7gkirgg86.apps.googleusercontent.com',
    iosClientId: '136939587877-9c7kiobmj76183gpe9tifc9etdfbknu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth2Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd-UKf86RVfOJMajSzGaCxCwxcEdcUCiM',
    appId: '1:136939587877:ios:350135454dafa6df0232cc',
    messagingSenderId: '136939587877',
    projectId: 'auth-flutter-ec8b3',
    storageBucket: 'auth-flutter-ec8b3.firebasestorage.app',
    androidClientId: '136939587877-avbbu7s79ptogdh5mcouoln7gkirgg86.apps.googleusercontent.com',
    iosClientId: '136939587877-9c7kiobmj76183gpe9tifc9etdfbknu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth2Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD142o849En4sc-Nr1NOKEt6XvlZgDQaBo',
    appId: '1:136939587877:web:e5f5caa54e2ad09b0232cc',
    messagingSenderId: '136939587877',
    projectId: 'auth-flutter-ec8b3',
    authDomain: 'auth-flutter-ec8b3.firebaseapp.com',
    storageBucket: 'auth-flutter-ec8b3.firebasestorage.app',
    measurementId: 'G-H3CRD9CQBS',
  );
}
